### ISSUE TITLE
Crash with QSL beta 17 

### ISSUE THREAD

**Issue by Spadgerr** [Lemonszz/Biome-Makeover#120]
---- Minecraft Crash Report ----
// My bad.

Time: 10/6/22, 5:22 pm
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'architectury'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:62)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:60)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:45)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:32)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.launch.knot.KnotHelper.launchClient(KnotHelper.java:28)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ExceptionInInitializerError
	at dev.architectury.registry.level.biome.BiomeModifications.addProperties(BiomeModifications.java)
	at party.lemons.biomemakeover.init.BMEntities.registerSpawn(BMEntities.java:252)
	at party.lemons.biomemakeover.init.BMEntities.initSpawns(BMEntities.java:149)
	at party.lemons.biomemakeover.init.BMEntities.initSpawnsAndAttributes(BMEntities.java:117)
	at party.lemons.biomemakeover.BiomeMakeover.lambda$init$5(BiomeMakeover.java:103)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
	at jdk.proxy3/jdk.proxy3.$Proxy35.run(Unknown Source)
	at dev.architectury.init.fabric.ArchitecturyClient.init(ArchitecturyClient.java:29)
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(Unknown Source)
	at jdk.proxy2/com.sun.proxy.jdk.proxy2.$Proxy34.onInitializeClient(Unknown Source)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$1(Hooks.java:53)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:32)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:58)
	... 21 more
Caused by: java.lang.ClassCastException: class dev.architectury.registry.level.biome.fabric.BiomeModificationsImpl$$Lambda$4314/0x0000000801607458 cannot be cast to class java.util.function.Consumer (dev.architectury.registry.level.biome.fabric.BiomeModificationsImpl$$Lambda$4314/0x0000000801607458 is in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @1e4d3ce5; java.util.function.Consumer is in module java.base of loader 'bootstrap')
	at net.fabricmc.fabric.api.biome.v1.BiomeModification.add(BiomeModification.java:64)
	at dev.architectury.registry.level.biome.fabric.BiomeModificationsImpl.registerModification(BiomeModificationsImpl.java:89)
	at dev.architectury.registry.level.biome.fabric.BiomeModificationsImpl.<clinit>(BiomeModificationsImpl.java:82)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:62)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:60)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:45)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:32)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.2203.5 (WinBuild.160101.0800):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.1151 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.27.29016.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Windows Lockdown Policy:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.19041.1503 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:OpenJDK Platform binary:17.0.3.0:Eclipse Adoptium
		javaw.exe:OpenJDK Platform binary:17.0.3.0:Eclipse Adoptium
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.3.0:Eclipse Adoptium
		jli.dll:OpenJDK Platform binary:17.0.3.0:Eclipse Adoptium
		jna13235637631978963305.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.3.0:Eclipse Adoptium
		jvm.dll:OpenJDK 64-Bit server VM:17.0.3.0:Eclipse Adoptium
		kernel.appcore.dll:AppModel API Host:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.3.0:Eclipse Adoptium
		management_ext.dll:OpenJDK Platform binary:17.0.3.0:Eclipse Adoptium
		msvcp140.dll:Microsoft® C Runtime Library:14.27.29016.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.3.0:Eclipse Adoptium
		nio.dll:OpenJDK Platform binary:17.0.3.0:Eclipse Adoptium
		ntdll.dll:NT Layer DLL:10.0.19041.1682 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.844 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.3.0:Eclipse Adoptium
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.27.29016.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.3.0:Eclipse Adoptium
		win32u.dll:Win32u:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.3.0:Eclipse Adoptium
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.launch.knot.KnotHelper.launchClient(KnotHelper.java:28)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1882803856 bytes (1795 MiB) / 2667577344 bytes (2544 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 4.01
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 980 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x17c8
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9613
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 27602.96
	Virtual memory used (MB): 14408.32
	Swap memory total (MB): 11264.00
	Swap memory used (MB): 1116.10
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8192m
	Quilted Fabric API: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		architectury: Architectury 4.4.70
		biomemakeover: Biome Makeover 1.18.2-1.4.24
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.2
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		quilt_base: Quilt Base API 1.1.0-beta.18+1.18.2
		quilt_biome: Quilt Biome API 1.1.0-beta.18+1.18.2
		quilt_block_extensions: Quilt Block Extensions API 1.1.0-beta.18+1.18.2
		quilt_client_command: Quilt Client Command API 1.1.0-beta.18+1.18.2
		quilt_command: Quilt Command API 1.1.0-beta.18+1.18.2
		quilt_crash_info: Quilt Crash Info 1.1.0-beta.18+1.18.2
		quilt_dimension: Quilt Dimension API 1.1.0-beta.18+1.18.2
		quilt_item_group: Quilt Item Group API 1.1.0-beta.18+1.18.2
		quilt_item_setting: Quilt Item Setting API 1.1.0-beta.18+1.18.2
		quilt_lifecycle_events: Quilt Lifecycle Events 1.1.0-beta.18+1.18.2
		quilt_loader: Quilt Loader 0.16.1
		quilt_networking: Quilt Networking 1.1.0-beta.18+1.18.2
		quilt_recipe: Quilt Recipe API 1.1.0-beta.18+1.18.2
		quilt_registry: Quilt Registry API 1.1.0-beta.18+1.18.2
		quilt_registry_entry_attachments: Quilt Registry Entry Attachments 1.1.0-beta.18+1.18.2
		quilt_resource_loader: Quilt Resource Loader 1.1.0-beta.18+1.18.2
		quilt_screen: Quilt Screen API 1.1.0-beta.18+1.18.2
		quilt_tags: Quilt Tags API 1.1.0-beta.18+1.18.2
		quilt_tooltip: Quilt Tooltip API 1.1.0-beta.18+1.18.2
		quilted_fabric_api: Quilted Fabric API 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_api_base: Quilted Fabric API Base 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_api_lookup_api_v1: Quilted Fabric API Lookup API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_biome_api_v1: Quilted Fabric Biome API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_blockrenderlayer_v1: Quilted Fabric BlockRenderLayer Registration (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_command_api_v1: Quilted Fabric Command API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_commands_v0: Quilted Fabric Commands (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_containers_v0: Quilted Fabric Containers (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_content_registries_v0: Quilted Fabric Content Registries (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_convention_tags_api_v1: Quilted Fabric Convention Tags API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_crash_report_info_v1: Quilted Fabric Crash Report Info (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_dimensions_v1: Quilted Fabric Dimensions API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_entity_events_v1: Quilted Fabric Entity Events (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_events_interaction_v0: Quilted Fabric Events Interaction (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_events_lifecycle_v0: Quilted Fabric Events Lifecycle (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_game_rule_api_v1: Quilted Fabric Game Rule API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_item_api_v1: Quilted Fabric Item API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_item_groups_v0: Quilted Fabric Item Groups (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_key_binding_api_v1: Quilted Fabric Key Binding API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_keybindings_v0: Quilted Fabric Key Bindings (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_lifecycle_events_v1: Quilted Fabric Lifecycle Events (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_loot_api_v2: Quilted Fabric Loot API (v2) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_loot_tables_v1: Quilted Fabric Loot Tables (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_mining_level_api_v1: Quilted Fabric Mining Level API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_models_v0: Quilted Fabric Models (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_networking_api_v1: Quilted Fabric Networking API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_networking_v0: Quilted Fabric Networking (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_object_builder_api_v1: Quilted Fabric Object Builder API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_particles_v1: Quilted Fabric Particles (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_registry_sync_v0: Quilted Fabric Registry Sync (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_renderer_api_v1: Quilted Fabric Renderer API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_renderer_indigo: Quilted Fabric Renderer - Indigo 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_renderer_registries_v1: Quilted Fabric Renderer Registries (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_rendering_data_attachment_v1: Quilted Fabric Rendering Data Attachment (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_rendering_fluids_v1: Quilted Fabric Rendering Fluids (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_rendering_v0: Quilted Fabric Rendering (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_rendering_v1: Quilted Fabric Rendering (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_resource_conditions_api_v1: Quilted Fabric Resource Conditions API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_resource_loader_v0: Quilted Fabric Resource Loader (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_screen_api_v1: Quilted Fabric Screen API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_screen_handler_api_v1: Quilted Fabric Screen Handler API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_textures_v0: Quilted Fabric Textures (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_transfer_api_v1: Quilted Fabric Transfer API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_transitive_access_wideners_v1: Quilted Fabric Transitive Access Wideners (v1) 1.0.0-beta.19+0.55.1-1.18.2
	Launched Version: PolyMC
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'
	Type: Client (map_client.txt)
	CPU: <unknown>
	Suspected Mods: Biome Makeover (biomemakeover), Quilt Loader (quilt_loader), Minecraft (minecraft), Architectury (architectury), Quilted Fabric Biome API (v1) (quilted_fabric_biome_api_v1)
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\spadg\AppData\Roaming\PolyMC\instances\Modpack Attempt Two\.minecraft\crash-reports\crash-2022-06-10_17.22.41-client.txt
Process exited with code -1.

**Comment by Lemonszz** [comment]
BM Quilt support is currently in a "if it work, it works. if it doesn't, it doesn't" stage.

At a glance, this looks to me more like an issue with Quilted Fabric API & Architectury than BM.
