### ISSUE TITLE
Game crashed because of Biome Makeover

### ISSUE THREAD

**Issue by Eatham532** [Lemonszz/Biome-Makeover#128]
Don't know why. Thought it was best that I let you know. Also using Chunky to generate chunks. 

**Log**

``` ---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 22/6/22, 5:14 pm
Description: Accessing LegacyRandomSource from multiple threads

java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.util.thread.LockHelper.crash(LockHelper:84)
	at net.minecraft.util.math.random.CheckedRandom.next(CheckedRandom:49)
	at net.minecraft.util.math.random.BaseRandom.nextInt(BaseRandom:33)
	at party.lemons.biomemakeover.level.WindSystem.update(WindSystem.java:16)
	at party.lemons.biomemakeover.level.BMWorldEvents.lambda$init$0(BMWorldEvents.java:44)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$13(EventHandlerImpl.java:66)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:62)
	at net.minecraft.server.MinecraftServer.handler$bje000$onEndTick(MinecraftServer:5316)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:857)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:98)
	at net.minecraft.server.MinecraftServer.handler$zmf000$modifiedRunLoop(MinecraftServer:3380)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:258)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_5798.method_33564(class_5798.java:84)

-- Thread dumps --
Details:
	Thread dumps: Server thread: 
	at java.base/java.lang.Thread.getStackTrace(Unknown Source)
	at net.minecraft.class_5798.method_39936(class_5798.java:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at net.minecraft.class_5798.method_33564(class_5798.java:82)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:33)
	at party.lemons.biomemakeover.level.WindSystem.update(WindSystem.java:16)
	at party.lemons.biomemakeover.level.BMWorldEvents.lambda$init$0(BMWorldEvents.java:44)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$13(EventHandlerImpl.java:66)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:62)
	at net.minecraft.server.MinecraftServer.handler$bje000$onEndTick(MinecraftServer.java:5316)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:857)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.handler$zmf000$modifiedRunLoop(MinecraftServer.java:3380)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Unknown Source)
Stacktrace:
	at net.minecraft.class_5798.method_33564(class_5798.java:84)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:33)
	at party.lemons.biomemakeover.level.WindSystem.update(WindSystem.java:16)
	at party.lemons.biomemakeover.level.BMWorldEvents.lambda$init$0(BMWorldEvents.java:44)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$13(EventHandlerImpl.java:66)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:62)
	at net.minecraft.server.MinecraftServer.handler$bje000$onEndTick(MinecraftServer.java:5316)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:857)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.handler$zmf000$modifiedRunLoop(MinecraftServer.java:3380)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 2335931056 bytes (2227 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 1.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Plus Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x8a5a
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9621
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 3.73
	Memory slot #0 type: LPDDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 3.73
	Memory slot #1 type: LPDDR4
	Virtual memory max (MB): 21025.86
	Virtual memory used (MB): 17855.49
	Swap memory total (MB): 13247.68
	Swap memory used (MB): 4150.42
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	Fabric Mods: 
		advancednetherite: Advanced Netherite 1.6.0-1.19
		adventurez: AdventureZ 1.4.14
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.7.27
		auudio: Auudio 1.0.3
		badpackets: Bad Packets 0.1.2
		bcc: BetterCompatibilityChecker fabric-2.0.1-build.15
		biomemakeover: Biome Makeover 1.19-beta-1.5.5
		boatcontainer: BoatContainer 1.1.0
		bobby: Bobby 4.0.0
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		bookshelf: Bookshelf 14.0.3
		bsvsb: Better Sodium Video Settings Button 3.0.0
		capes: Capes 1.4.3+1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		carpet: Carpet Mod 1.4.79
		chunky: Chunky 1.2.202
		cloth-config: Cloth Config v6 7.0.72
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+3
		customizableelytra: Customizable Elytra 1.6.0-1.19
		deathknell: DeathKnell 4.0.1
		drippyloadingscreen: Drippy Loading Screen 1.6.4
		dynview: Dynamic View Mod 1.19-2.2
		ecs: Elytra/Chestplate Swapper 1.2.1-MC1.19
		emotecraft: Emotecraft 2.1.3-SNAPSHOT-build.30
			bendy-lib: Bendy api 2.0.4
		enchdesc: EnchantmentDescriptions 11.0.4
		endrem: End Remastered 5.1.0
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		fabric: Fabric API 0.56.1+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+82552130a9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.0+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.27+72da3b3da9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.24+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.2+9e7660c6a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.9+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.6+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.16+92cf9a3ea9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.7+c57dbccaa9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.4+db8596f1a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.23+9ff28f40a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.0+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.17.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		fancymenu: FancyMenu 2.8.0
		ferritecore: FerriteCore 4.2.1
		friendsandfoes: Friends&Foes 1.5.4
			mm: Manningham Mills 2.3
		fwaystones: Fabric Waystones 3.0.1+mc1.19
		goml: Get Off My Lawn ReServed 1.5.0-pre.3+1.19
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.0-beta.1
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			hologram-api: Hologram API 0.2.2+1.19
			placeholder-api: Placeholder API 2.0.0-beta.5+1.19
			playerabilitylib: Pal 1.6.0
			polymer: Polymer (Core) 0.2.0+1.19
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
			rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
			server_translations_api: Server Translations API 1.4.14+1.19-rc2
			sgui: sgui 1.1.0+1.19
		guardvillagers: Guard Villagers Fabric 1.19-1.0.14
		ias: In-Game Account Switcher 7.2.0
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		konkrete: Konkrete 1.3.3
		krypton: Krypton 0.2.0
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.8.0
		mcwpaintings: Macaw's Paintings 1.0.3
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.0
		more-axolotls: More Axolotls 1.0.2
		morebannerfeatures: More Banner Features 1.1.3
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		portal_accessibility: Nether Portal Accessibility 1.0.0-mc1.19
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.19-build.43
		respawnablepets: Respawnable Pets 1.19-2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			midnightlib: MidnightLib 0.5.2
		roughlyenoughitems: Roughly Enough Items 9.0.491
		shulkerboxtooltip: Shulker Box Tooltip 3.0.9+1.19
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.5+mc1.19-build.43
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		starlight: Starlight 1.1.1+fabric.ae22326
		trade_cycling: Trade Cycling 1.19-1.0.2
		trinkets: Trinkets 3.4.0
		universal-graves: Universal Graves 2.0.5+1.19
		voicechat: Simple Voice Chat 1.19-2.2.46
		voidz: VoidZ 1.0.8
		wi_zoom: WI Zoom 1.4-MC1.19
		wildfirefly: Wild FireFly 1.1-release
		wthit: wthit 5.4.3
		xaerominimap: Xaero's Minimap 22.9.2
		xaeroworldmap: Xaero's World Map 1.23.2
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 1 / 8; [class_3222['Eatham532'/170, l='ServerLevel[AdventureZ Test]', x=-236.01, y=-42.00, z=-141.43]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.19
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 1
	Suspected Mods: Biome Makeover (biomemakeover), Architectury (architectury) ```

**Comment by Lemonszz** [comment]
Thanks for the report - fixed for 1.5.6
