### ISSUE TITLE
[1.19] [Fabric] World crashing a few seconds after loading.

### ISSUE THREAD

**Issue by KateReller** [Lemonszz/Biome-Makeover#139]
I have been using [WorldGen](https://github.com/caeruleusDraconis/WorldGen) to generate my worlds. When I'm done, I start my world and after a few seconds, I crash. 

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 7/16/22, 2:46 PM
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1513)
	at party.lemons.biomemakeover.util.task.TaskManager.tick(TaskManager.java:24)
	at party.lemons.biomemakeover.util.task.TaskManager.lambda$init$0(TaskManager.java:14)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
	at jdk.proxy2/jdk.proxy2.$Proxy125.tick(Unknown Source)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$15(EventHandlerImpl.java:68)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108)
	at net.minecraft.class_3218.handler$bmp000$endWorldTick(class_3218.java:8228)
	at net.minecraft.class_3218.method_18765(class_3218.java:383)
	at net.minecraft.server.MinecraftServer.md69e84c$lambda$tickWorlds$0$5(MinecraftServer.java:7310)
	at wearblackallday.dimthread.DimThread.swapThreadsAndRun(DimThread.java:34)
	at net.minecraft.server.MinecraftServer.md69e84c$lambda$tickWorlds$1$4(MinecraftServer.java:7308)
	at wearblackallday.util.ThreadPool.lambda$execute$1(ThreadPool.java:49)
	at wearblackallday.util.ThreadPool.lambda$execute$0(ThreadPool.java:43)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1513)
	at party.lemons.biomemakeover.util.task.TaskManager.tick(TaskManager.java:24)
	at party.lemons.biomemakeover.util.task.TaskManager.lambda$init$0(TaskManager.java:14)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
	at jdk.proxy2/jdk.proxy2.$Proxy125.tick(Unknown Source)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$15(EventHandlerImpl.java:68)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108)
	at net.minecraft.class_3218.handler$bmp000$endWorldTick(class_3218.java:8228)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 0
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (472,64,-664), Section: (at 8,0,8 in 29,4,-42; chunk contains blocks 464,0,-672 to 479,255,-657), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Level time: 94 game time, 94 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 124002 (now: false), thunder time: 161454 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at wearblackallday.dimthread.util.CrashInfo.crash(CrashInfo.java:11)
	at net.minecraft.server.MinecraftServer.handler$bil000$tickWorlds(MinecraftServer.java:7320)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:864)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.handler$zok000$modifiedRunLoop(MinecraftServer.java:5380)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 5140027904 bytes (4901 MiB) / 9529458688 bytes (9088 MiB) up to 9529458688 bytes (9088 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Virtual Desktop Monitor
	Graphics card #0 vendor: Virtual Desktop, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=15.39.56.845
	Graphics card #1 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2489
	Graphics card #1 versionInfo: DriverVersion=31.0.15.1659
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29644.59
	Virtual memory used (MB): 21565.40
	Swap memory total (MB): 13312.00
	Swap memory used (MB): 2077.09
	JVM Flags: 64 total; -XX:ThreadPriorityPolicy=1 -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:-UnlockExperimentalVMOptions -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:-UseBiasedLocking -XX:+EnableJVMCIProduct -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+EagerJVMCI -XX:UseAVX=2 -XX:+UseStringDeduplication -XX:+UseFastUnorderedTimeStamps -XX:+UseAES -XX:+UseAESIntrinsics -XX:UseSSE=4 -XX:AllocatePrefetchStyle=1 -XX:+UseLoopPredicate -XX:+RangeCheckElimination -XX:+EliminateLocks -XX:+DoEscapeAnalysis -XX:+UseCodeCacheFlushing -XX:+UseFastJNIAccessors -XX:+OptimizeStringConcat -XX:+UseCompressedOops -XX:+UseThreadPriorities -XX:+OmitStackTraceInFastThrow -XX:+TrustFinalNonStaticFields -XX:ThreadPriorityPolicy=1 -XX:+UseInlineCaches -XX:+RewriteBytecodes -XX:+RewriteFrequentPairs -XX:+UseNUMA -XX:-DontCompileHugeMethods -XX:+UseCMoveUnconditionally -XX:+UseFPUForSpilling -XX:+UseNewLongLShift -XX:+UseVectorCmov -XX:+UseXMMForArrayCopy -XX:+UseXmmI2D -XX:+UseXmmI2F -XX:+UseXmmLoadAndClearUpper -XX:+UseXmmRegToRegMoveAll -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms9088m -Xmx9088m
	Fabric Mods: 
		additionalbars: Additional Bars 3.3.1+1.19
		additionalstructures: Additional Structures 4.0.0
		adorn: Adorn 3.5.4+1.19
		allstackable: AllStackable v1.5.5-1.19
		alternate-current: Alternate Current 1.4.0
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.19
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.9.31
		automodpack: AutoModpack 2.1.3
		axolotlitemfix: Axolotl Item Fix 1.1.3
		balm-fabric: Balm 4.3.0+0
		beaconoverhaul: Beacon Overhaul 1.7.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		biomemakeover: Biome Makeover 1.19-1.5.8
		bookshelf: Bookshelf 14.1.7
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.1-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		cacao: Croptopia's Chocolaterie 1.2
		cardinal-components: Cardinal Components API 4.2.0
			cardinal-components-block: Cardinal Components API (blocks) 4.2.0
			cardinal-components-chunk: Cardinal Components API (chunks) 4.2.0
			cardinal-components-item: Cardinal Components API (items) 4.2.0
			cardinal-components-level: Cardinal Components API (world saves) 4.2.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.2.0
			cardinal-components-world: Cardinal Components API (worlds) 4.2.0
		carpet: Carpet Mod 1.4.80
		cloth-config: Cloth Config v6 7.0.72
			cloth-basic-math: cloth-basic-math 0.6.1
		cookingforblockheads: Cooking for Blockheads 13.1.2
		crops_love_rain: Crops Love Rain 1.3.0
		croptopia: Croptopia 2.0.7
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		dawn: Dawn API 3.5.0
		deathlog: DeathLog 0.2.10+1.19
		difficultytweaker: Difficulty Tweaker 0.3.0+1.19
		dimthread: DimensionalThreading 1.2.7
			com_github_wearblackallday_javautils: JavaUtils bd58640372
		discerning_furnace: Discerning Furnace 1.0.7
		egg-of-capitalism: Egg Of Capitalism 3.1
		emi: EMI 0.2.0+1.19-rc2
		enchanted-vertical-slabs: Enchanted Vertical Slabs 1.5
		fabric: Fabric API 0.57.0+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		fallingtree: FallingTree 3.7.1
		fastload: Fast Load 1.1.5
		ferritecore: FerriteCore 4.2.1
		fractalportals: FractalPortals 1.5.1
			customportalapi: Custom Portal Api 0.0.1-beta51-1.19
		frame: Frame 0.22.2+1.19
			frame-api-base: Frame Base 0.2.0
			frame-blocks-v0: Frame Blocks (v0) 0.1.2
			frame-config-v0: Frame Config (v0) 0.2.1
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.3
			frame-items-v0: Frame Items (v0) 0.1.2
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4
			frame-rendering-v0: Frame Rendering (v0) 0.1.4
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.1
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.0+c2d5b470a9
			frame-woods-v0: Frame Woods (v0) 0.1.0+ea73347fa9
		friendlyfire: FriendlyFire 12.0.1
		fwaystones: Fabric Waystones 3.0.2+mc1.19
		geckolib3: Geckolib 3.1.5
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		gilded: Gilded Netherite 1.0.2
		goat-horn-noise-mod: Goat Horn Noise Mod 1.0.0
		graveyard: The Graveyard 1.10
		infinitywaterbucket: Infinity Water Bucket 2.0.0
		inmis: Inmis 2.7.0-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		inventorio: Inventorio 1.8.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		keepheadnames: Keep Head Names 1.5.1
		kleeslabs: KleeSlabs 12.0.0
		krypton: Krypton 0.2.0
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		lengthyladders: Lengthy Ladders 1.0.5
		lithium: Lithium 0.8.1
		mavm: More Axolotl Variants Mod 1.1.0
		mcwbridges: Macaw's Bridges 2.0.3
		mcwdoors: Macaw's Doors 1.0.6
		mcwroofs: Macaw's Roofs 2.1.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.6
		mcwwindows: Macaw's Windows 2.0.3
		mcxr-core: [MCXR] Core 0.2.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			org_joml_joml: joml 1.10.4
		mealapi: Meal API 0.3.1+1.19
			cloth-config-lite: cloth-config-lite 2.0.6
		memoryleakfix: memory Leak Fix 1.19-0.4.1
		minecraft: Minecraft 1.19
		minegate-moreblocks: MineGate · MoreBlocks 1.2.5
		missingwilds: Missing Wilds 1.1.1
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		moremcmeta: MoreMcmeta 1.19-3.0.4
		naturalist: Naturalist 2.0.1
		numismatic-overhaul: Numismatic Overhaul 0.2.3+1.19
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			stacc: Stacc 1.3.3
		nyfsquiver: Nyf's Quivers Fabric-0.5.0-1.19-rc2
		overpoweredmending: OverpoweredMending 2.5.1
		owo: oωo 0.7.3+1.19
		pandamc_concreteplus: Concrete Plus 1.9.5
		patchouli: Patchouli 1.19-74-FABRIC
			fiber: fiber 0.23.0-2
		perfectaccuracy: Perfect Accuracy 1.2-1.19
		pigeons: Pleasant Pigeons 1.5.0+fabric
		qcraft: qCraft Reimagined 1.2.0
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		randomtp: Random Teleport Mod 7.0.0+1.19
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		repurposed_structures: Repurposed Structures 6.1.1+1.19
			midnightlib: MidnightLib 0.5.2
		right-click-harvest: Right-Click-Harvest 1.2.0
		sandwichable: Sandwichable 1.3.a+1.19
			spruceui: SpruceUI 4.0.0+1.19
		servercore: ServerCore 1.3.0-1.19
		sleepwarp: SleepWarp 1.2.0+1.19
		smoothboot: Smooth Boot 1.19-1.7.1
		spark: spark 1.9.13
		styled-nicknames: Styled Nicknames 1.1.1+1.19
			player-data-api: Player Data API 0.1.0+1.18
		styledchat: Styled Chat 1.3.3+1.19
			placeholder-api: Placeholder API 2.0.0-beta.7+1.19
		subterrestrial: Subterrestrial 1.0.3
		t_and_t: Towns and Towers - Structure Add-on 1.7
		taxfreelevels: Tax Free Levels 1.3
		tempad: Tempad 1.2.5
		terralith: Terralith 2.3
		textile_backup: Textile Backup 2.4.0-1.19
			com_github_shevek_parallelgzip: parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
			org_apache_commons_commons-compress: commons-compress 1.21
			org_tukaani_xz: xz 1.9
		the_extractinator: The Extractinator 1.10
		toms_storage: Tom's Simple Storage Mod 1.3.5
		trade_cycling: Trade Cycling 1.19-1.0.3
		trinkets: Trinkets 3.4.0
		twigs: Twigs 2.0.0-beta.8+1.19
		universal-graves: Universal Graves 2.1.0+1.19
			common-protection-api: Common Protection API 1.0.0
			hologram-api: Hologram API 0.2.2+1.19
			polymer: Polymer (Core) 0.2.2+1.19
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.1+1.19
			server_translations_api: Server Translations API 1.4.16+1.19
			sgui: sgui 1.1.1+1.19
		universal_ores: Universal Ores 1.4.1
		unsaddle: Unsaddle 0.1.0+1.17
			unsaddle-core: Unsaddle Core 0.1.0
		walllanterns: Lanterns Belong on Walls 1.2.1
		wardenloot: Warden Loot 1.0.9-1.19.x
		wooltostring: Wool-to-String 1.0.2
		world-gen: WorldGen 1.0.0
		yippee: Yippee 1.0.0
	Server Running: true
	Player Count: 1 / 8; [class_3222['Kate_Reller'/9757, l='ServerLevel[New World]', x=472.50, y=60.19, z=-663.50]]
	Data Packs: vanilla, Fabric Mods, minecraft/croptop
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.19

**Comment by Lemonszz** [comment]
I can probably get a fix out for this shortly.
In the mean time, there's a good chance removing Dimensional Threading would stop the crash.
