### ISSUE TITLE
Crash with default Minecraft launcher

### ISSUE THREAD

**Issue by Anwaikurn** [Lemonszz/Biome-Makeover#147]
Hello!
There is a very strange bug that I catch. It appears when the game starts with the default Minecraft launcher (or CurseForge launcher).
But everything works well, for example in GDLauncher (I tried only this one as an alternative).

I thought that can be caused by the java version, but GDL and CurseForge use the same one.

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 08.08.22, 03:53
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'biomemakeover'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: Trying to access unbound value 'air' from registry Registry[ResourceKey[minecraft:root / minecraft:item] (Experimental)]
	at net.minecraft.class_6880$class_6883.method_40237(class_6880.java:151)
	at net.minecraft.class_6880$class_6883.method_40230(class_6880.java:196)
	at dev.architectury.extensions.injected.InjectedRegistryEntryExtension.arch$registryName(InjectedRegistryEntryExtension.java:32)
	at dev.architectury.core.item.ArchitecturySpawnEggItem.lambda$new$0(ArchitecturySpawnEggItem.java:77)
	at dev.architectury.registry.registries.Registrar.lambda$listen$0(Registrar.java:83)
	at dev.architectury.registry.registries.fabric.RegistriesImpl$RegistrarImpl.listen(RegistriesImpl.java:285)
	at dev.architectury.registry.registries.Registrar.listen(Registrar.java:83)
	at dev.architectury.registry.registries.RegistrySupplier.listen(RegistrySupplier.java:110)
	at dev.architectury.core.item.ArchitecturySpawnEggItem.<init>(ArchitecturySpawnEggItem.java:76)
	at dev.architectury.core.item.ArchitecturySpawnEggItem.<init>(ArchitecturySpawnEggItem.java:68)
	at party.lemons.biomemakeover.init.BMItems.lambda$static$37(BMItems.java:99)
	at dev.architectury.registry.registries.fabric.RegistriesImpl$RegistrarImpl.register(RegistriesImpl.java:223)
	at dev.architectury.registry.registries.DeferredRegister.register(DeferredRegister.java:76)
	at party.lemons.biomemakeover.init.BMItems.init(BMItems.java:131)
	at party.lemons.biomemakeover.BiomeMakeover.init(BiomeMakeover.java:39)
	at party.lemons.biomemakeover.fabric.BMFabric.onInitialize(BMFabric.java:59)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 908661088 bytes (866 MiB) / 1543503872 bytes (1472 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3,80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x2216
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1659
	Memory slot #0 capacity (MB): 16384,00
	Memory slot #0 clockSpeed (GHz): 3,60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384,00
	Memory slot #1 clockSpeed (GHz): 3,60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 58271,96
	Virtual memory used (MB): 19342,61
	Swap memory total (MB): 25600,00
	Swap memory used (MB): 53,16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		architectury: Architectury 4.8.80
		biomemakeover: Biome Makeover 1.18.2-1.4.29
		fabric: Fabric API 0.58.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.1+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.19+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.2+17cbbd4360
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.10+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.3+41a02c8a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabricloader: Fabric Loader 0.14.9
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.2
	Launched Version: fabric-loader-0.14.9-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by Lemonszz** [comment]
That's strange.

Could you try it with this version of architectury and tell me if it works or not?

https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/3786590

**Comment by Anwaikurn** [comment]
With this version of architectury everything works fine.

**Comment by Lemonszz** [comment]
Cool, thanks for testing - that pretty much tracks it down.

I'll get a fixed version out soonish.

**Comment by Anwaikurn** [comment]
And I also tried the newer version architectury-4.7.78 - also no issues at all. 

But it broke starting from architectury-4.8.79.

**Comment by Lemonszz** [comment]
Should be fixed on the latest versions of architectury. No BM update needed.

Give me a shout if it persists.
