### ISSUE TITLE
Biome MakerOver spamming log with errors

### ISSUE THREAD

**Issue by Zelioth** [Lemonszz/Biome-Makeover#156]
Came acorss a few issues in my custom mod pack, which is also published on Curse forge if you wish to recreate. "Friends United v2.0.6" Seems to be spamming with a bunch of issues didn't know if it was worth reporting but could possible fix broken features.
[latest.log](https://github.com/Lemonszz/Biome-Makeover/files/9436859/latest.log)

**Comment by Zelioth** [comment]
[latest.log](https://github.com/Lemonszz/Biome-Makeover/files/9440464/latest.log)

just wanna show Biome Makeover is the main issue at this point. Hope this helps with future updates

**Comment by Zelioth** [comment]
[06Oct2022 01:38:53.515] [Worker-Main-16/WARN] [dev.architectury.registry.client.particle.forge.ParticleProviderRegistryImpl/]: Something is attempting to register particle providers at a later point than intended! This might cause issues!
java.lang.Throwable: null
	at dev.architectury.registry.client.particle.forge.ParticleProviderRegistryImpl.register(ParticleProviderRegistryImpl.java:101) ~[architectury-6.2.46-forge.jar%23176!/:?]
	at dev.architectury.registry.client.particle.ParticleProviderRegistry.register(ParticleProviderRegistry.java) ~[architectury-6.2.46-forge.jar%23176!/:?]
	at party.lemons.biomemakeover.init.BMEffects.lambda$init$4(BMEffects.java:116) ~[biomemakeover-FORGE-1.19.2-1.5.12.jar%23203!/:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-6.2.46-forge.jar%23176!/:?]
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-6.2.46-forge.jar%23176!/:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%23115!/:?]
	at jdk.proxy3.$Proxy101.stateChanged(Unknown Source) ~[?:?]
	at dev.architectury.event.forge.EventHandlerImplClient$ModBasedEventHandler.event(EventHandlerImplClient.java:341) ~[architectury-6.2.46-forge.jar%23176!/:?]
	at dev.architectury.event.forge.__ModBasedEventHandler_event_FMLClientSetupEvent.invoke(.dynamic) ~[architectury-6.2.46-forge.jar%23176!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.1.33.jar%23560!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.2-43.1.33.jar%23559!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[06Oct2022 01:38:53.521] [Worker-Main-16/WARN] [dev.architectury.registry.client.particle.forge.ParticleProviderRegistryImpl/]: Something is attempting to register particle providers at a later point than intended! This might cause issues!
java.lang.Throwable: null
	at dev.architectury.registry.client.particle.forge.ParticleProviderRegistryImpl.register(ParticleProviderRegistryImpl.java:101) ~[architectury-6.2.46-forge.jar%23176!/:?]
	at dev.architectury.registry.client.particle.ParticleProviderRegistry.register(ParticleProviderRegistry.java) ~[architectury-6.2.46-forge.jar%23176!/:?]
	at party.lemons.biomemakeover.init.BMEffects.lambda$init$4(BMEffects.java:117) ~[biomemakeover-FORGE-1.19.2-1.5.12.jar%23203!/:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-6.2.46-forge.jar%23176!/:?]
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-6.2.46-forge.jar%23176!/:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%23115!/:?]
	at jdk.proxy3.$Proxy101.stateChanged(Unknown Source) ~[?:?]
	at dev.architectury.event.forge.EventHandlerImplClient$ModBasedEventHandler.event(EventHandlerImplClient.java:341) ~[architectury-6.2.46-forge.jar%23176!/:?]
	at dev.architectury.event.forge.__ModBasedEventHandler_event_FMLClientSetupEvent.invoke(.dynamic) ~[architectury-6.2.46-forge.jar%23176!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.1.33.jar%23560!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.2-43.1.33.jar%23559!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
