### ISSUE TITLE
Ghost entity causing server crash when specific player logs in

### ISSUE THREAD

**Issue by GoetiaP** [Lemonszz/Biome-Makeover#188]
Seeing an odd issue when user OverlordDyvone, shown in the log, logs into the server.
Is there perhaps a way to disable the ghost mob for the time being?

We play on 1.18.2, Fabric

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 12/14/22, 3:47 PM
Description: Ticking entity

java.lang.NullPointerException: Parameter specified as non-null is null: method com.github.quiltservertools.ledger.callbacks.BlockChangeCallback$DefaultImpls.changeBlock, parameter player
	at com.github.quiltservertools.ledger.callbacks.BlockChangeCallback$DefaultImpls.changeBlock(BlockChangeCallback.kt)
	at com.github.quiltservertools.ledger.callbacks.BlockChangeCallback$Companion$EVENT$1$1.changeBlock(BlockChangeCallback.kt:34)
	at net.minecraft.class_2401.args$cfe000$logLeverUse(class_2401.java:534)
	at net.minecraft.class_2401.method_21846(class_2401.java:110)
	at party.lemons.biomemakeover.level.PoltergeistHandler.lambda$static$3(PoltergeistHandler.java:65)
	at party.lemons.biomemakeover.level.PoltergeistHandler.doBehaviour(PoltergeistHandler.java:156)
	at party.lemons.biomemakeover.level.PoltergeistHandler.doPoltergeist(PoltergeistHandler.java:129)
	at party.lemons.biomemakeover.entity.GhostEntity$PoltergeistGoal.method_6268(GhostEntity.java:421)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:119)
	at net.minecraft.class_1355.method_6275(class_1355.java:110)
	at net.minecraft.class_1308.method_6023(class_1308.java:742)
	at net.minecraft.class_1309.method_6007(class_1309.java:2609)
	at net.minecraft.class_1308.method_6007(class_1308.java:546)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1308.method_5773(class_1308.java:346)
	at party.lemons.biomemakeover.entity.GhostEntity.method_5773(GhostEntity.java:96)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.quiltservertools.ledger.callbacks.BlockChangeCallback$DefaultImpls.changeBlock(BlockChangeCallback.kt)
	at com.github.quiltservertools.ledger.callbacks.BlockChangeCallback$Companion$EVENT$1$1.changeBlock(BlockChangeCallback.kt:34)
	at net.minecraft.class_2401.args$cfe000$logLeverUse(class_2401.java:534)
	at net.minecraft.class_2401.method_21846(class_2401.java:110)
	at party.lemons.biomemakeover.level.PoltergeistHandler.lambda$static$3(PoltergeistHandler.java:65)
	at party.lemons.biomemakeover.level.PoltergeistHandler.doBehaviour(PoltergeistHandler.java:156)
	at party.lemons.biomemakeover.level.PoltergeistHandler.doPoltergeist(PoltergeistHandler.java:129)
	at party.lemons.biomemakeover.entity.GhostEntity$PoltergeistGoal.method_6268(GhostEntity.java:421)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:119)
	at net.minecraft.class_1355.method_6275(class_1355.java:110)
	at net.minecraft.class_1308.method_6023(class_1308.java:742)
	at net.minecraft.class_1309.method_6007(class_1309.java:2609)
	at net.minecraft.class_1308.method_6007(class_1308.java:546)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1308.method_5773(class_1308.java:346)
	at party.lemons.biomemakeover.entity.GhostEntity.method_5773(GhostEntity.java:96)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)

-- Entity being ticked --
Details:
	Entity Type: biomemakeover:ghost (party.lemons.biomemakeover.entity.GhostEntity)
	Entity ID: 1192
	Entity Name: entity.biomemakeover.ghost
	Entity's Exact location: -476.51, 67.28, 2261.28
	Entity's Block location: World: (-477,67,2261), Section: (at 3,3,5 in -30,4,141; chunk contains blocks -480,-64,2256 to -465,319,2271), Region: (-1,4; contains chunks -32,128 to -1,159, blocks -512,-64,2048 to -1,319,2559)
	Entity's Momentum: -0.04, -0.09, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 2 total; [class_3222['paimonxx'/130, l='ServerLevel[SMPWorld]', x=-636.05, y=71.00, z=683.77], class_3222['OverlordDyvone'/464, l='ServerLevel[SMPWorld]', x=-422.38, y=61.00, z=2225.62]]
	Chunk stats: 5742
	Level dimension: minecraft:overworld
	Level spawn location: World: (-970,71,683), Section: (at 6,7,11 in -61,4,42; chunk contains blocks -976,-64,672 to -961,319,687), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,-64,512 to -513,319,1023)
	Level time: 37727646 game time, 1886896 day time
	Level name: SMPWorld
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 4.19.0-17-amd64
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2843609088 bytes (2711 MiB) / 6933184512 bytes (6612 MiB) up to 8388608000 bytes (8000 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900 12-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 166861.59
	Virtual memory used (MB): 102717.23
	Swap memory total (MB): 102400.00
	Swap memory used (MB): 25630.86
	JVM Flags: 3 total; -XX:+UseContainerSupport -Xms128M -Xmx8000M
	Fabric Mods: 
		additionalbars: Additional Bars 3.3.1+1.18.2
		alloy_forgery: Alloy Forgery 2.0.13+1.18
		another_furniture: Another Furniture 1.2.2-1.18.2
		appleskin: AppleSkin 2.4.1+mc1.18.2
		architects_palette: Architect's Palette Fabric 2.2
		architectury: Architectury 4.10.86
		attributefix: AttributeFix 14.0.2
		autoconfig1u: Auto Config v1 Updated 3.4.0
		automobility: Automobility 0.2.1+1.18.2
			jsonem: JsonEM 0.1.2
			myron: Myron 1.6.3+1.18.1
		autotag: AutoTag 1.1.0
		balm-fabric: Balm 3.2.0+0
		bclib: BCLib 1.4.7
		bettercombat: Better Combat 1.4.5+1.18.2
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.2
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		biomemakeover: Biome Makeover 1.18.2-1.4.32
		blockus: Blockus 2.4.8+1.18.2
			terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		byg: Oh The Biomes You'll Go 1.4
		carrier: Carrier 1.10.0
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		chimes: Chimes 1.1.1
		chipped: Chipped 2.0.0
		chisel: Chisel Refabricated 1.4.5
		chunky: Chunky 1.2.164
		cloth-config: Cloth Config v6 6.4.90
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 8.0.0+15
		cobbled_paths: Cobbled Paths 0.1.7
		collective-fabric: Collective (Fabric) 5.14
			fiber: fiber 0.23.0-2
		combatroll: Combat Roll 1.0.8+1.18.2
		completeconfig: CompleteConfig 1.4.1
		connectivity: Connectivity Mod 1.18.2-3.3
		couplings: Couplings 1.8.0+1.18.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		crawl: Crawl 0.10.6
			mm: Manningham Mills 2.3
		create: Create 0.5.0e-733
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.3.0
			forge_tags: Forge Tags 2.1
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			porting_lib: Porting Lib 1.2.460-beta+1.18.2-dev.cca931b
				com_github_llamalad7_mixinextras: MixinExtras 0.0.11
				serialization_hooks: Serialization Hooks 0.3.23
			reach-entity-attributes: Reach Entity Attributes 2.1.1
			registrate-fabric: Registrate for Fabric MC1.18.2-1.1.4
		creatures_from_the_warmths: Creatures From The Warmths 2.1.0+1.18.2
		creeperoverhaul: Creeper Overhaul 1.3.1
		cyti: Can You Trash It? 1.0.6
			team_reborn_energy: Energy 2.2.0
		debugify: Debugify 1.11.0
		decorative_blocks: Decorative Blocks 2.1.1
		diamondeconomy: Diamond Economy 1.5.0
			org_xerial_sqlite-jdbc: sqlite-jdbc 3.36.0.3
			placeholder-api: Placeholder API 1.1.3+1.17.1
		dramaticdoors: Dramatic Doors (Fabric) 1.18.2-1.3.3_1
		duckling: Duckling 1.0.7
		dustrial_decor: Dustrial Decor 0.5
		ecologics: Ecologics 1.7.10
		editsign: EditSign 2.3.1
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		emotecraft: Emotecraft 2.2.5
		essential_commands: Essential Commands 0.24.5-mc1.18.2
			com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.13.0
			ec-core: Essential Commands Core 1.0.1-mc1.18.2
		extraorigins: Extra Origins 1.18-12
		fabric-api: Fabric API 0.59.1+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.2+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.19+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.2+17cbbd4360
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.11+bb2e047760
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.5+kotlin.1.7.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.4
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.10
		fallingtree: FallingTree 3.5.4
		fancymenu: FancyMenu 2.12.6
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 3.2.4
		friendsandfoes: Friends&Foes 1.4.5
		ftblibrary: FTB Library 1802.3.7-build.154
		ftbquests: FTB Quests 1802.3.9-build.130
		ftbteams: FTB Teams 1802.2.7-build.71
		geckolib3: Geckolib 3.0.64
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 19
		globaldataandresourcepacks: Global Data- & Resourcepacks 1.12.3_fabric
		go-fish: Go Fish 1.5.0-1.18.2
		goodall: Goodall 1.0.2
		harvest_scythes: Harvest Scythes 2.5.3+mc1.18.2
		hollowwoods: HollowWoods 1.2.0
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
		hyle: Hyle 0.1.0
		iceberg: Iceberg 1.0.38
		immersive_paintings: Immersive Paintings 0.3.1+1.18.2
		impaled: Impaled 1.1.3
		inmis: Inmis 2.6.0-1.18.2
		inmisaddon: InmisAddon 1.0.1-1.18
		inventorysorter: Inventory Sorter 1.8.8-1.18
			kyrptconfig: Kyrpt Config 1.4.6-1.18
				blue_endless_jankson: jankson 1.2.1
		itemfilters: Item Filters 1802.2.8-build.47
		jade: Jade 5.99.9
		java: OpenJDK 64-Bit Server VM 17
		jumpy-boats: jumpy Boats 1.0-1.18.2
		keepmysoiltilled-fabric: Keep My Soil Tilled (Fabric) 1.7
		kiwi: Kiwi Lib 6.0.2
		konkrete: Konkrete 1.5.3
		lazydfu: LazyDFU 0.1.2
		ledger: Ledger 1.2.4
		lightingwand: Lighting Wand 4.0.0
		lilwings: Lil' Wings 1.2.3
		lithium: Lithium 0.7.10
		lootr: Lootr 0.3.23.60
		lovely_snails: Lovely Snails 1.0.4+1.18
		luckperms: LuckPerms 5.4.25
		luckperms-placeholders: LuckPerms Placeholders 5.1-SNAPSHOT
		mantori: Aphid Additions 1.1.1-1.18.2
		marketcrates: Marketcrates 1.4.1
		mermaid: Mod 1.0.0
		minecraft: Minecraft 1.18.2
		mob_catcher: Mob Catcher 1.1.29
		modid: Creatures Of The Snow 2.1.0+1.18.2
		morebannerfeatures: More Banner Features 1.1.3
		morevillagers: More Villagers 3.3.2
		mosslayers: Moss Layers 1.0.1
		mostructures: Mo' Structures 1.4.2+1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		multibeds: MultiBeds 1.2.6
		mythicmetals: Mythic Metals 0.16.3+1.18.2
		mythicmounts: Mythic Mounts 1.18.2-7.0
		mythorigins: Myth Origins 0.1.1
		naturalist: Naturalist 1.1.1
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		netherportalfix: NetherPortalFix 9.0.0
		not_enough_gamerules: Not Enough Gamerules 1.4.2-release
		offhandcombat: Off Hand Combat 0.0.4
		opaccreatesupport: OPAC Create Mod Support 1.1.0
		openpartiesandclaims: Open Parties and Claims 0.15.0
		origins: Origins 1.4.1
			apoli: Apoli 2.3.3
				additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
				calio: Calio 1.5.1
				playerabilitylib: Pal 1.5.0
		origins-classes: Origins: Classes 1.3.0
		owo: oωo 0.7.2-no-cme+1.18
		patchouli: Patchouli 1.18.2-71.1-FABRIC
		pehkui: Pehkui 3.6.0+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		player-animator: Player Animator 0.3.5
		polymorph: Polymorph 0.0.21-1.18.2
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-block: Cardinal Components API (blocks) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
			cardinal-components-item: Cardinal Components API (items) 4.1.4
		questsadditions: Quests Additions 1.4.0
		reaping: Reaping 2.1.5
		repurposed_structures: Repurposed Structures 4.1.14+1.18.2
		roughlyenoughitems: Roughly Enough Items 8.3.563
			error_notifier: Error Notifier 1.0.9
		sentimentality3: Sentimentality 3 1.5.0
		shetiphiancore: ShetiPhianCore 1.2.15
		sit: Sit 1.18.2-19
		skylorlib: SkyLib 1.5.1-1.18.2
		sprout: Sprout 1.3.1
		structory: Structory 1.0.0
		styled-nicknames: Styled Nicknames 1.0.4+1.18
		styledchat: Styled Chat 1.2.3+1.18
		styledplayerlist: Styled Player List 2.1.3+1.18
			player-data-api: Player Data API 0.1.0+1.18
		surfacemushrooms-fabric: Surface Mushrooms (Fabric) 2.0
		t_and_t: Towns and Towers 1.9-B
		taterzens: Taterzens 1.9.6
			config2brigadier: Config to Brigadier 1.1.1
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			server_translations_api: Server Translations API 1.4.12+1.18.2
				packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
			sgui: sgui 1.0.0+1.18.1
		tawct: Time & Wind Custom Ticker 1.4.2+1.18.2
		terrablender: TerraBlender 1.2.0.126
		tokenablefurnaces: Tokenable Furnaces 1.1.6
		tradernpcs: Trader NPCs 1.1.1
		trashslot: TrashSlot 11.0.2
		trinketofundying: Trinket of Undying 2.0.2-1.18.2
		trinkets: Trinkets 3.3.1
		trulytreasures: Truly Treasures fabric-1.18.1-2.0.1
		twigs: Twigs 1.1.3-patch2+1.18.2
		unearthed: Unearthed 2.3.3
		unvotedandshelved: Unvoted & Shelved 2.0.1
		vanityslots: Vanity Slots 1.1.2
		variant_bookshelves: Variant Bookshelves 1.2.2
		vehiclefix: VehicleFix 3.3
		voicechat: Simple Voice Chat 1.18.2-2.3.12
		weaponmaster: YDM's Weapon Master 3.0.2
		welcomemessage-fabric: Welcome Message (Fabric) 1.8
		worldedit: WorldEdit 7.2.10+1742f98
		xaerominimap: Xaero's Minimap 22.16.0
		xaeroworldmap: Xaero's World Map 1.28.1
		xlpackets: XLPackets 2.1-1.17.1
		yigd: You're in Grave Danger 1.3.10
		yungsapi: YUNG's API 1.18.2-Fabric-2.2.6
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
	Server Running: true
	Player Count: 2 / 50; [class_3222['paimonxx'/130, l='ServerLevel[SMPWorld]', x=-636.05, y=71.00, z=683.77], class_3222['OverlordDyvone'/464, l='ServerLevel[SMPWorld]', x=-422.38, y=61.00, z=2225.62]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Lemonszz** [comment]
https://github.com/Lemonszz/Biome-Makeover/issues/131
