### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by BrekiTomasson** [Lemonszz/Biome-Makeover#39]
Using v1.3.3, getting this on launch:

```

[10:48:48] [main/ERROR]: Couldn't parse loot table biomemakeover:blocks/ectoplasm_composter
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'biomemakeover:composter'
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.4) ~[?:?]
	at net.minecraft.util.JsonHelper.method_17995(JsonHelper:127) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_282]
	at net.minecraft.util.JsonHelper.asItem(JsonHelper:127) ~[?:?]
	at net.minecraft.util.JsonHelper.getItem(JsonHelper:135) ~[?:?]
	at net.minecraft.loot.entry.ItemEntry$Serializer.fromJson(ItemEntry:55) ~[?:?]
	at net.minecraft.loot.entry.ItemEntry$Serializer.fromJson(ItemEntry:40) ~[?:?]
	at net.minecraft.loot.entry.LeafEntry$Serializer.fromJson(LeafEntry:151) ~[?:?]
	at net.minecraft.loot.entry.LeafEntry$Serializer.fromJson(LeafEntry:129) ~[?:?]
	at net.minecraft.loot.entry.LootPoolEntry$Serializer.fromJson(LootPoolEntry:86) ~[?:?]
	at net.minecraft.loot.entry.LootPoolEntry$Serializer.fromJson(LootPoolEntry:74) ~[?:?]
	at net.minecraft.util.JsonSerializing$GsonSerializer.deserialize(JsonSerializing:83) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.0.jar:?]
	at net.minecraft.util.JsonHelper.deserialize(JsonHelper:440) ~[?:?]
	at net.minecraft.util.JsonHelper.deserialize(JsonHelper:448) ~[?:?]
```

**Comment by Lemonszz** [comment]
Thanks - Going to reupload 1.3.3 with this fixed.

**Comment by Lemonszz** [comment]
Done - https://www.curseforge.com/minecraft/mc-mods/biome-makeover/files/3274628
