### ISSUE TITLE
Mixin conflict with More Tags

### ISSUE THREAD

**Issue by curtlog** [Lemonszz/Biome-Makeover#68]
Crashes on startup when [Paradise Lost](https://github.com/devs-immortal/Paradise-Lost) is installed with Biome Makeover. Using 1.18.1-1.4.2 Biome Makeover and the newest dev Paradise Lost commit 6c8eb17, from github action [1699461730](https://github.com/devs-immortal/Paradise-Lost/actions/runs/1699461730).

<details>
<summary>Error Log</summary>
<pre><code>[09:12:11] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[09:12:12] [main/INFO]: Loading 61 mods:
	- architectury 3.4.9
	- biomemakeover 1.18.1-1.4.2
	- cardinal-components-base 4.0.1 via the_aether
	- cardinal-components-entity 4.0.1 via the_aether
	- crowdin-translate 1.3+1.17 via the_aether
	- customportalapi 0.0.1-beta48-1.18 via the_aether
	- fabric 0.46.2+1.18
	- fabric-api-base 0.4.1+b4f4f6cd3a via fabric
	- fabric-api-lookup-api-v1 1.5.1+17be577f3a via fabric
	- fabric-biome-api-v1 6.0.1+ded849a93a via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d953a via fabric
	- fabric-command-api-v1 1.1.6+3ac43d953a via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd3a via fabric
	- fabric-containers-v0 0.1.18+d154e2c63a via fabric
	- fabric-content-registries-v0 0.4.6+6f53a73d3a via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d953a via fabric
	- fabric-dimensions-v1 2.1.9+a1d9bbf53a via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a3a via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f173a via fabric
	- fabric-events-lifecycle-v0 0.2.7+b4f4f6cd3a via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d953a via fabric
	- fabric-item-api-v1 1.3.0+691a79b53a via fabric
	- fabric-item-groups-v0 0.3.4+3ac43d953a via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f33a via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cd3a via fabric
	- fabric-lifecycle-events-v1 1.4.11+e66b59e93a via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d953a via fabric
	- fabric-mining-level-api-v1 1.0.4+3ac43d953a via fabric
	- fabric-mining-levels-v0 0.1.9+b4f4f6cd3a via fabric
	- fabric-models-v0 0.3.3+3ac43d953a via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d953a via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd3a via fabric
	- fabric-object-builder-api-v1 1.11.2+3b82842e3a via fabric
	- fabric-object-builders-v0 0.7.10+3ac43d953a via fabric
	- fabric-particles-v1 0.2.9+526dc1ac3a via fabric
	- fabric-registry-sync-v0 0.9.0+befed49e3a via fabric
	- fabric-renderer-api-v1 0.4.10+b0b66fc33a via fabric
	- fabric-renderer-indigo 0.4.13+b0b66fc33a via fabric
	- fabric-renderer-registries-v1 3.2.8+b4f4f6cd3a via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d73a via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d953a via fabric
	- fabric-rendering-v0 1.1.10+b4f4f6cd3a via fabric
	- fabric-rendering-v1 1.10.4+e66b59e93a via fabric
	- fabric-resource-conditions-api-v1 1.0.1+13eda0653a via fabric
	- fabric-resource-loader-v0 0.4.12+e66b59e93a via fabric
	- fabric-screen-api-v1 1.0.7+3ac43d953a via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d953a via fabric
	- fabric-structure-api-v1 2.1.1+0a73a6c23a via fabric
	- fabric-tag-extensions-v0 1.2.6+3ac43d953a via fabric
	- fabric-textures-v0 1.0.9+3ac43d953a via fabric
	- fabric-tool-attribute-api-v1 1.3.6+fb3b57b43a via fabric
	- fabric-transfer-api-v1 1.5.7+b4f4f6cd3a via fabric
	- fabricloader 0.12.12
	- gud_recipe_confidence 1.0.2 via the_aether
	- incubus_core 1.6.3 via the_aether
	- java 17
	- minecraft 1.18.1
	- moretags 1.4.8 via the_aether
	- reach-entity-attributes 2.1.1 via the_aether
	- the_aether 1.18.1-1.6.4
	- trinkets 3.1.0 via the_aether
[09:12:12] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/.../libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[09:12:12] [main/INFO]: Compatibility level set to JAVA_16
[09:12:12] [main/INFO]: Compatibility level set to JAVA_17
[09:12:12] [main/WARN]: Reference map 'biomemakeover-fabric-refmap.json' for biomemakeover.mixins.json could not be read. If this is a development environment you can ignore this message
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Callback Metafactory Transformer]
[09:12:14] [main/WARN]: @Redirect conflict. Skipping moretags.mixins.json:farmland.CropBlockMixin->@Redirect::isBlockFarmland(Lnet/minecraft/class_2680;Lnet/minecraft/class_2248;)Z from mod moretags with priority 1000, already redirected by biomemakeover-common.mixins.json:CropBlockMixin->@Redirect::isFarmland(Lnet/minecraft/class_2680;Lnet/minecraft/class_2248;)Z from mod biomemakeover with priority 1000
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Callback Metafactory Transformer]
[21:20:28] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[minecraft-1.18.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 10 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2302 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[minecraft-1.18.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[minecraft-1.18.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 10 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector isBlockFarmland(Lnet/minecraft/class_2680;Lnet/minecraft/class_2248;)Z in moretags.mixins.json:farmland.CropBlockMixin from mod moretags failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap MoreTags-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+moixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[minecraft-1.18.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 10 more
Process exited with code 1.</code></pre>
</details>

**Comment by curtlog** [comment]
`[08:59:24] [main/WARN]: @Redirect conflict. Skipping moretags.mixins.json:farmland.CropBlockMixin->@Redirect::isBlockFarmland(Lnet/minecraft/class_2680;Lnet/minecraft/class_2248;)Z from mod moretags with priority 1000, already redirected by biomemakeover-common.mixins.json:CropBlockMixin->@Redirect::isFarmland(Lnet/minecraft/class_2680;Lnet/minecraft/class_2248;)Z from mod biomemakeover with priority 1000`
It's caused by a dependency, [More Tags](https://github.com/gudenau/minecraft-MoreTags/), that has a redirect mixin with an alike target to your mod. This seems to create issues with many mods.

[Here](https://github.com/paulevsGitch/BCLib/issues/42) is a relevant issue where this same problem happened with one of the other mods from the same author and BCLib.

**Comment by Lemonszz** [comment]
Fixed for next version
