### ISSUE TITLE
Can't Load in Dev Environment

### ISSUE THREAD

**Issue by gudenau** [Lemonszz/Biome-Makeover#93]
When attempting to do research into a compatibility issue with More Tags I ran into an issue where I could not run Biome Makeover in a development environment.

The mod fails to remap because of a duplicated method in both `p.l.b.e.a.MountedCrossbowAttackGoal` (`canStart()V`) and `p.l.b.e.GhostEntity` (`chooseRandomAngerTime()V`).

Log:
```
[23:58:30] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[23:58:30] [main/INFO] (FabricLoader) Loading 65 mods:
	- architectury 3.7.33
	- biomemakeover 1.18.1-1.4.8
	- byg 1.3.5.13
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- com_electronwill_night-config_core 3.6.4 via terrablender
	- com_electronwill_night-config_toml 3.6.4 via terrablender
	- com_typesafe_config 1.4.1 via confabricate
	- confabricate 2.2.0-SNAPSHOT+4.1.1 via croptopia
	- croptopia 1.8.3
	- fabric 0.47.10+1.18.2
	- fabric-api-base 0.4.3+d7c144a860
	- fabric-api-lookup-api-v1 1.5.6+d7c144a860
	- fabric-biome-api-v1 8.0.2+801ec85b60
	- fabric-blockrenderlayer-v1 1.1.11+3ac43d9560
	- fabric-command-api-v1 1.1.8+d7c144a860
	- fabric-commands-v0 0.2.7+b4f4f6cd60
	- fabric-containers-v0 0.1.20+d7c144a860
	- fabric-content-registries-v0 3.0.1+d82b939260
	- fabric-crash-report-info-v1 0.1.10+3ac43d9560
	- fabric-data-generation-api-v1 2.0.6+b5a7ab5360
	- fabric-dimensions-v1 2.1.16+2540745460
	- fabric-entity-events-v1 1.4.7+d7c144a860
	- fabric-events-interaction-v0 0.4.18+d7c144a860
	- fabric-events-lifecycle-v0 0.2.12+d7c144a860
	- fabric-game-rule-api-v1 1.0.12+d7c144a860
	- fabric-gametest-api-v1 1.0.14+2540745460
	- fabric-item-api-v1 1.3.2+691a79b560
	- fabric-item-groups-v0 0.3.9+3ac43d9560
	- fabric-key-binding-api-v1 1.0.11+54e5b2ec60
	- fabric-keybindings-v0 0.2.9+b4f4f6cd60
	- fabric-lifecycle-events-v1 2.0.1+2540745460
	- fabric-loot-tables-v1 1.0.10+d7c144a860
	- fabric-mining-level-api-v1 2.0.3+d1027f7d60
	- fabric-models-v0 0.3.5+d7c144a860
	- fabric-networking-api-v1 1.0.20+d882b91560
	- fabric-networking-v0 0.3.7+b4f4f6cd60
	- fabric-object-builder-api-v1 2.0.2+34b2a0ce60
	- fabric-particles-v1 0.2.11+526dc1ac60
	- fabric-registry-sync-v0 0.9.7+0d9ab37260
	- fabric-renderer-api-v1 0.4.12+d882b91560
	- fabric-renderer-indigo 0.4.16+d8c7b9ae60
	- fabric-renderer-registries-v1 3.2.10+b4f4f6cd60
	- fabric-rendering-data-attachment-v1 0.3.6+d7c144a860
	- fabric-rendering-fluids-v1 2.0.1+54e5b2ec60
	- fabric-rendering-v0 1.1.12+b4f4f6cd60
	- fabric-rendering-v1 1.10.6+54e5b2ec60
	- fabric-resource-conditions-api-v1 2.0.1+d1027f7d60
	- fabric-resource-loader-v0 0.4.17+801ec85b60
	- fabric-screen-api-v1 1.0.9+d882b91560
	- fabric-screen-handler-api-v1 1.1.13+d7c144a860
	- fabric-textures-v0 1.0.11+3ac43d9560
	- fabric-transfer-api-v1 1.5.13+cca23f9360
	- fabricloader 0.13.3
	- farmersdelight 1.18.1-0.2.0
	- io_leangen_geantyref_geantyref 1.3.11 via confabricate
	- java 17
	- minecraft 1.18.2
	- moretags 3.0.3
	- org_spongepowered_configurate-core 4.1.1 via confabricate
	- org_spongepowered_configurate-extra-dfu4 4.1.1 via confabricate
	- org_spongepowered_configurate-gson 4.1.1 via confabricate
	- org_spongepowered_configurate-hocon 4.1.1 via confabricate
	- roughlyenoughitems 7.3.443
	- terrablender 1.1.0.77
Mapping target name conflicts detected:
  METHODs party/lemons/biomemakeover/entity/ai/MountedCrossbowAttackGoal/[canStart, net/minecraft/class_1352/method_6264]()Z -> canStart
  METHODs party/lemons/biomemakeover/entity/GhostEntity/[chooseRandomAngerTime, net/minecraft/class_5354/method_29509]()V -> chooseRandomAngerTime
There were unfixable conflicts.
[23:58:36] [main/ERROR] (FabricLoader) Failed to remap mods!
 net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Unfixable conflicts
	at net.fabricmc.loader.impl.discovery.RuntimeModRemapper.remap(RuntimeModRemapper.java:174) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:260) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.RuntimeException: Unfixable conflicts
	at net.fabricmc.tinyremapper.TinyRemapper.handleConflicts(TinyRemapper.java:861) ~[tiny-remapper-0.8.1.jar:0.8.1]
	at net.fabricmc.tinyremapper.TinyRemapper.propagate(TinyRemapper.java:761) ~[tiny-remapper-0.8.1.jar:0.8.1]
	at net.fabricmc.tinyremapper.TinyRemapper.mrjRefresh(TinyRemapper.java:1040) ~[tiny-remapper-0.8.1.jar:0.8.1]
	at net.fabricmc.tinyremapper.TinyRemapper.apply(TinyRemapper.java:892) ~[tiny-remapper-0.8.1.jar:0.8.1]
	at net.fabricmc.loader.impl.discovery.RuntimeModRemapper.remap(RuntimeModRemapper.java:120) ~[fabric-loader-0.13.3.jar:?]
	... 6 more
```

I have never seen this before, not sure how one would go about fixing this.

**Comment by Lemonszz** [comment]
Yeah I have no clue either lol.

Looks like you're trying to load a 1.18.1 version in 1.18.2 though, which almost certainly wont work.

What's the MoreTags issue?

**Comment by gudenau** [comment]
Looks like it might be Architectury causing problems here. It doesn't use Yarn so the names can collide.

Apparently there are a couple of mods that prevent farmland from working correctly in More Tags.

**Comment by gudenau** [comment]
Not your fault, should probably rename the methods though.
