### ISSUE TITLE
Not recognizing Architectury 3.7.38 as valid (Works OK w/ 3.7.37)

### ISSUE THREAD

**Issue by Tursiops-G** [Lemonszz/Biome-Makeover#95]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install architectury, version 3.6.15 or later.
Unmet dependency listing:
	 - Mod 'Biome Makeover' (biomemakeover) 1.18.1-1.4.8 requires version 3.6.15 or later of architectury, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by Lemonszz** [comment]
odd. ill check it out later, but make sure you're not using the forge version of arch

**Comment by Tursiops-G** [comment]
Downloaded it straight from the Fabric page. Shouldn't be Forge (Unless They mixed up the repositories somehow...)

**Comment by Lemonszz** [comment]
Closing this as I can confirm it works on my end.

It's VERY likely you've downloaded the forge version OR it's not in the mods folder, as it tells you what version you currently have if it can recognize the .jar and it's an invalid version.

![image](https://user-images.githubusercontent.com/7577248/162551194-3316dcc3-9689-4a9a-8d24-0644e90c52de.png)

**Comment by Lemonszz** [comment]
Also you're on a very old version of BM

**Comment by Tursiops-G** [comment]
I'm using 1.18.1 (not 1.18.2), and BM 1.18.1-1.4.8 (Latest available for 1.18.1 according to Curseforge).
Curseforge Link to BM: https://www.curseforge.com/minecraft/mc-mods/biome-makeover/files/3667657
If there's a newer 1.18.1 version available, it hasn't yet made it to CF, AFAICT

And I DID use the 1.18.1 (Fabric) Architectury (Also latest according to Curseforge).
Curseforge link to Architectury (Fabric): https://www.curseforge.com/minecraft/mc-mods/architectury-fabric/files/3728612

I JUST D/L'ed it Again, and NOW it works.... :o

Since BOTH the Forge and Fabric D/L files themselves seem to have the Exact SAME Name, I'll Assume that there was a CF Screwup, and they were serving the wrong file on the Fabric page... (?)

Anyway, the problem has now been corrected. :)  Thank You for your prompt response to the issue.

Cheers!
